user_auth_info_from: file # OSENV or file
user_auth_info_file_location: tests/testdata/user_settings.ini
private_key_file_location: default
public_key_file_location: default
fernet_key_file: tests/testdata/prod_farnetkeys
